document.addEventListener("DOMContentLoaded",()=>{
  const q=s=>document.querySelector(s), menu=q("#mobileMenu"), menuBtn=q(".menu-button");
  if(menuBtn&&menu){menuBtn.addEventListener("click",()=>{const open=menuBtn.getAttribute("aria-expanded")==="true";menuBtn.setAttribute("aria-expanded",String(!open));menuBtn.setAttribute("aria-label",!open?"Close menu":"Open menu");menuBtn.classList.toggle("is-open",!open);menu.hidden=open;});}
  document.querySelectorAll(".mobile-nav a,.desktop-nav a,.footer-nav a").forEach(a=>a.addEventListener("click",()=>{if(menu&&menuBtn){menu.hidden=true;menuBtn.setAttribute("aria-expanded","false");menuBtn.setAttribute("aria-label","Open menu");menuBtn.classList.remove("is-open");}}));
  const reduceMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const initCarousel=(rootSelector,trackSelector,slideSelector,prevSelector,nextSelector,currentSelector)=>{
    const root=q(rootSelector);if(!root)return;const track=root.querySelector(trackSelector),slides=[...root.querySelectorAll(slideSelector)],prev=root.querySelector(prevSelector),next=root.querySelector(nextSelector),current=root.querySelector(currentSelector);if(!track||!slides.length)return;
    let index=0,resizeFrame=0,busy=false,unlockTimer=0;
    const update=()=>{track.style.transform=`translate3d(-${index*100}%,0,0)`;if(prev)prev.disabled=index===0;if(next)next.disabled=index===slides.length-1;if(current)current.textContent=String(index+1).padStart(2,"0");};
    const go=delta=>{if(busy)return;const target=Math.min(slides.length-1,Math.max(0,index+delta));if(target===index)return;index=target;update();if(reduceMotion)return;busy=true;clearTimeout(unlockTimer);unlockTimer=window.setTimeout(()=>{busy=false;},560);};
    prev?.addEventListener("click",()=>go(-1));next?.addEventListener("click",()=>go(1));
    let startX=0,startY=0;root.addEventListener("touchstart",e=>{const t=e.changedTouches[0];startX=t.clientX;startY=t.clientY},{passive:true});root.addEventListener("touchend",e=>{const t=e.changedTouches[0],dx=t.clientX-startX,dy=t.clientY-startY;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))go(dx<0?1:-1)},{passive:true});
    window.addEventListener("resize",()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(update)},{passive:true});update();
  };
  const carousel=q("[data-projects-carousel]");
  if(carousel){const track=carousel.querySelector(".projects-track"),cards=[...carousel.querySelectorAll(".project-card")],prev=q(".projects-prev"),next=q(".projects-next"),current=q(".projects-pagination-current");let index=0,resizeFrame=0,busy=false,unlockTimer=0;const isMobile=()=>window.matchMedia("(max-width:800px)").matches;const maxIndex=()=>isMobile()?Math.max(0,cards.length-1):Math.max(0,cards.length-2);const desktopTransform=()=>`translate3d(calc(-${index*50}% - ${index*7}px),0,0)`;const update=()=>{if(!track)return;const mobile=isMobile();track.style.transform=mobile?`translate3d(-${index*100}%,0,0)`:desktopTransform();if(prev)prev.disabled=index===0;if(next)next.disabled=index>=maxIndex();if(current)current.textContent=String(index+1).padStart(2,"0");};const go=delta=>{if(busy)return;const target=Math.min(maxIndex(),Math.max(0,index+delta));if(target===index)return;index=target;update();if(reduceMotion)return;busy=true;clearTimeout(unlockTimer);unlockTimer=window.setTimeout(()=>{busy=false;},560);};prev?.addEventListener("click",()=>go(-1));next?.addEventListener("click",()=>go(1));window.addEventListener("resize",()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>{index=Math.min(index,maxIndex());update();});},{passive:true});let startX=0,startY=0;carousel.addEventListener("touchstart",e=>{const t=e.changedTouches[0];startX=t.clientX;startY=t.clientY},{passive:true});carousel.addEventListener("touchend",e=>{const t=e.changedTouches[0],dx=t.clientX-startX,dy=t.clientY-startY;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))go(dx<0?1:-1)},{passive:true});update();}
  initCarousel("[data-build-carousel]",".build-track",".build-slide",".build-prev",".build-next",".build-pagination-current");

});
